image: tiangolo/docker-with-compose

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - pip install docker-auto-labels

stages:
  - test
  - build
  - deploy

tests:
  stage: test
  script:
    - sh ./scripts/test.sh
  tags:
    - build
    - test

deploy-stag:
  stage: deploy
  script: 
    - >
      DOMAIN=stag.jusan.com
      TRAEFIK_TAG=stag.jusan.com
      STACK_NAME=stag-jusan-com
      TAG=stag
      sh ./scripts/deploy.sh
  environment:
    name: staging
    url: https://stag.jusan.com
  only:
    - master
  tags:
    - swarm
    - stag

deploy-prod:
  stage: deploy
  script:
    - >
      DOMAIN=jusan.com
      TRAEFIK_TAG=jusan.com
      STACK_NAME=jusan-com
      TAG=prod
      sh ./scripts/deploy.sh
  environment:
    name: production
    url: https://jusan.com
  only:
    - production
  tags:
    - swarm
    - prod
