default_context:
  project_name: 'jusan'
  project_slug: 'jusan'
  domain_main: 'jusan.com'
  domain_staging: 'stag.jusan.com'
  docker_swarm_stack_name_main: 'jusan-com'
  docker_swarm_stack_name_staging: 'stag-jusan-com'
  secret_key: 'rprgwEHG0WCcruC32RtMuWFuBnjNA0IL'
  first_superuser: 'admin@jusan.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.jusan.com", "https://stag.jusan.com", "https://jusan.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@jusan.com'
  postgres_password: 'jusan'
  pgadmin_default_user: 'admin@jusan.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'jusan.com'
  traefik_constraint_tag_staging: 'stag.jusan.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: 'https://e47c262785844f2f972f3b077012f2d5@o4504348664725504.ingest.sentry.io/4504348696379392'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
