"""transaction log refactor

Revision ID: 54e4229fcbaa
Revises: 234a164ec00d
Create Date: 2022-12-28 08:58:17.509571+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e4229fcbaa'
down_revision = '234a164ec00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_log', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('transaction_log', sa.Column('recipient_account_id', sa.Integer(), nullable=True))
    op.drop_constraint('transaction_log_item_id_fkey', 'transaction_log', type_='foreignkey')
    op.drop_constraint('transaction_log_recipient_id_fkey', 'transaction_log', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_log', 'user_account', ['recipient_account_id'], ['id'])
    op.create_foreign_key(None, 'transaction_log', 'order', ['order_id'], ['id'])
    op.drop_column('transaction_log', 'item_id')
    op.drop_column('transaction_log', 'recipient_id')
    op.add_column('user_account', sa.Column('expiration_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'expiration_date')
    op.add_column('transaction_log', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transaction_log', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction_log', type_='foreignkey')
    op.drop_constraint(None, 'transaction_log', type_='foreignkey')
    op.create_foreign_key('transaction_log_recipient_id_fkey', 'transaction_log', 'user', ['recipient_id'], ['id'])
    op.create_foreign_key('transaction_log_item_id_fkey', 'transaction_log', 'item', ['item_id'], ['id'])
    op.drop_column('transaction_log', 'recipient_account_id')
    op.drop_column('transaction_log', 'order_id')
    # ### end Alembic commands ###
